#
#  DO NOT EDIT THIS FILE
#  all it does is merge the various Gemfile.* files
#
#

source 'https://rubygems.org'

['rails','boilerplate','app'].each do |gemfile|
  eval File.read('Gemfile.'+gemfile), nil, 'Gemfile.'+gemfile
end